// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIyl9QqMu26tgr_BK6vUrV7uGtmrMc5E',
    appId: '1:390658496608:web:6fe75f0d30de75f32f0b05',
    messagingSenderId: '390658496608',
    projectId: 'ecommerceapp-c9ea3',
    authDomain: 'ecommerceapp-c9ea3.firebaseapp.com',
    storageBucket: 'ecommerceapp-c9ea3.firebasestorage.app',
    measurementId: 'G-MMBCSZ3Q4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJbwqO1TgojxZcybE3OIX4qo74KswD9Y',
    appId: '1:390658496608:android:53b5a0a39441bcb52f0b05',
    messagingSenderId: '390658496608',
    projectId: 'ecommerceapp-c9ea3',
    storageBucket: 'ecommerceapp-c9ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDND-1o5qHX7mq0e6IziJEMZsDirb_uI4k',
    appId: '1:390658496608:ios:7cceb0ecb6640fd72f0b05',
    messagingSenderId: '390658496608',
    projectId: 'ecommerceapp-c9ea3',
    storageBucket: 'ecommerceapp-c9ea3.firebasestorage.app',
    androidClientId: '390658496608-1imm0ad4qdr2mac03qe5g01deee8t3op.apps.googleusercontent.com',
    iosClientId: '390658496608-jt0c99e4qso0ffab655uloa5ou6dj7b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}